#! /bin/bash

source venv/bin/activate

python train.py \
     --data_root=data \
     --sessions_root=sessions \
     --data_folder=bach_multiinstrumental \
     --session_folder=bach_2048_hop_1024  \
     --use_cpu=True \
     --gold_standard="Fugue"
deactivate
